// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace Authors

open System
open System.Data
open Authors.Readers

module Sqls =

  [<Literal>]
  let getAuthor =
    """
    SELECT id, name, bio FROM authors
WHERE id = @id LIMIT 1
  """

  [<Literal>]
  let listAuthors =
    """
    SELECT id, name, bio FROM authors
ORDER BY name
  """

  [<Literal>]
  let createAuthor =
    """
    INSERT INTO authors (
  name, bio
) VALUES (
  @name, @bio
)
  """

  [<Literal>]
  let deleteAuthor =
    """
    DELETE FROM authors
WHERE id = @id
  """

[<RequireQualifiedAccessAttribute>]
type DB(conn: IDbConnection) =

  member this.getAuthor(id: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.getAuthor
    let p_id = cmd.CreateParameter()
    p_id.ParameterName <- "@id"
    p_id.Value <- box id
    cmd.Parameters.Add(p_id) |> ignore
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (authorReader rdr) :: results

    List.rev results

  member this.listAuthors() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.listAuthors
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (authorReader rdr) :: results

    List.rev results

  member this.createAuthor(name: string, ?bio: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.createAuthor
    let p_name = cmd.CreateParameter()
    p_name.ParameterName <- "@name"
    p_name.Value <- box name
    cmd.Parameters.Add(p_name) |> ignore
    let p_bio = cmd.CreateParameter()
    p_bio.ParameterName <- "@bio"

    p_bio.Value <-
      match bio with
      | Some v -> box v
      | None -> box DBNull.Value

    cmd.Parameters.Add(p_bio) |> ignore
    cmd.ExecuteNonQuery()

  member this.deleteAuthor(id: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.deleteAuthor
    let p_id = cmd.CreateParameter()
    p_id.ParameterName <- "@id"
    p_id.Value <- box id
    cmd.Parameters.Add(p_id) |> ignore
    cmd.ExecuteNonQuery()
