// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace Authors

open System
open System.Data

module Readers =

  let authorReader (r: IDataReader) : Author =
    {
      Author.Id = r.GetInt32(r.GetOrdinal("id"))
      Name = r.GetString(r.GetOrdinal("name"))
      Bio = if r.IsDBNull(r.GetOrdinal("bio")) then None else Some(r.GetString(r.GetOrdinal("bio")))
    }
