// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace Booktest

open System
open System.Data

type Author = { AuthorId: int; Name: string }

type Book =
  {
    BookId: int
    AuthorId: int
    Isbn: string
    BookType: string
    Title: string
    Yr: int
    Available: DateTime
    Tags: string
  }

type BooksByTagsRow = { BookId: int; Title: string; Name: string option; Isbn: string; Tags: string }
