// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace Booktest

open System
open System.Data
open Booktest.Readers

module Sqls =

  [<Literal>]
  let getAuthor =
    """
    SELECT author_id, name FROM authors
WHERE author_id = ?
  """

  [<Literal>]
  let getBook =
    """
    SELECT book_id, author_id, isbn, book_type, title, yr, available, tags FROM books
WHERE book_id = ?
  """

  [<Literal>]
  let deleteBook =
    """
    DELETE FROM books
WHERE book_id = ?
  """

  [<Literal>]
  let booksByTitleYear =
    """
    SELECT book_id, author_id, isbn, book_type, title, yr, available, tags FROM books
WHERE title = ? AND yr = ?
  """

  [<Literal>]
  let booksByTags =
    """
    SELECT
  book_id,
  title,
  name,
  isbn,
  tags
FROM books
LEFT JOIN authors ON books.author_id = authors.author_id
WHERE tags = ?
  """

  [<Literal>]
  let createAuthor =
    """
    INSERT INTO authors (name) VALUES (?)
  """

  [<Literal>]
  let createBook =
    """
    INSERT INTO books (
    author_id,
    isbn,
    book_type,
    title,
    yr,
    available,
    tags
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
  """

  [<Literal>]
  let updateBook =
    """
    UPDATE books
SET title = ?, tags = ?
WHERE book_id = ?
  """

  [<Literal>]
  let updateBookISBN =
    """
    UPDATE books
SET title = ?, tags = ?, isbn = ?
WHERE book_id = ?
  """

  [<Literal>]
  let deleteAuthorBeforeYear =
    """
    DELETE FROM books
WHERE yr < ? AND author_id = ?
  """

[<RequireQualifiedAccessAttribute>]
type DB(conn: IDbConnection) =

  member this.getAuthor(authorId: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.getAuthor
    let p_authorId = cmd.CreateParameter()
    p_authorId.ParameterName <- "@author_id"
    p_authorId.Value <- box authorId
    cmd.Parameters.Add(p_authorId) |> ignore
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (authorReader rdr) :: results

    List.rev results

  member this.getBook(bookId: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.getBook
    let p_bookId = cmd.CreateParameter()
    p_bookId.ParameterName <- "@book_id"
    p_bookId.Value <- box bookId
    cmd.Parameters.Add(p_bookId) |> ignore
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (bookReader rdr) :: results

    List.rev results

  member this.deleteBook(bookId: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.deleteBook
    let p_bookId = cmd.CreateParameter()
    p_bookId.ParameterName <- "@book_id"
    p_bookId.Value <- box bookId
    cmd.Parameters.Add(p_bookId) |> ignore
    cmd.ExecuteNonQuery()

  member this.booksByTitleYear(title: string, yr: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.booksByTitleYear
    let p_title = cmd.CreateParameter()
    p_title.ParameterName <- "@title"
    p_title.Value <- box title
    cmd.Parameters.Add(p_title) |> ignore
    let p_yr = cmd.CreateParameter()
    p_yr.ParameterName <- "@yr"
    p_yr.Value <- box yr
    cmd.Parameters.Add(p_yr) |> ignore
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (bookReader rdr) :: results

    List.rev results

  member this.booksByTags(tags: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.booksByTags
    let p_tags = cmd.CreateParameter()
    p_tags.ParameterName <- "@tags"
    p_tags.Value <- box tags
    cmd.Parameters.Add(p_tags) |> ignore
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (booksByTagsRowReader rdr) :: results

    List.rev results

  member this.createAuthor(name: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.createAuthor
    let p_name = cmd.CreateParameter()
    p_name.ParameterName <- "@name"
    p_name.Value <- box name
    cmd.Parameters.Add(p_name) |> ignore
    cmd.ExecuteNonQuery()

  member this.createBook
    (authorId: int, isbn: string, bookType: string, title: string, yr: int, available: DateTime, tags: string)
    =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.createBook
    let p_authorId = cmd.CreateParameter()
    p_authorId.ParameterName <- "@author_id"
    p_authorId.Value <- box authorId
    cmd.Parameters.Add(p_authorId) |> ignore
    let p_isbn = cmd.CreateParameter()
    p_isbn.ParameterName <- "@isbn"
    p_isbn.Value <- box isbn
    cmd.Parameters.Add(p_isbn) |> ignore
    let p_bookType = cmd.CreateParameter()
    p_bookType.ParameterName <- "@book_type"
    p_bookType.Value <- box bookType
    cmd.Parameters.Add(p_bookType) |> ignore
    let p_title = cmd.CreateParameter()
    p_title.ParameterName <- "@title"
    p_title.Value <- box title
    cmd.Parameters.Add(p_title) |> ignore
    let p_yr = cmd.CreateParameter()
    p_yr.ParameterName <- "@yr"
    p_yr.Value <- box yr
    cmd.Parameters.Add(p_yr) |> ignore
    let p_available = cmd.CreateParameter()
    p_available.ParameterName <- "@available"
    p_available.Value <- box available
    cmd.Parameters.Add(p_available) |> ignore
    let p_tags = cmd.CreateParameter()
    p_tags.ParameterName <- "@tags"
    p_tags.Value <- box tags
    cmd.Parameters.Add(p_tags) |> ignore
    cmd.ExecuteNonQuery()

  member this.updateBook(title: string, tags: string, bookId: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.updateBook
    let p_title = cmd.CreateParameter()
    p_title.ParameterName <- "@title"
    p_title.Value <- box title
    cmd.Parameters.Add(p_title) |> ignore
    let p_tags = cmd.CreateParameter()
    p_tags.ParameterName <- "@tags"
    p_tags.Value <- box tags
    cmd.Parameters.Add(p_tags) |> ignore
    let p_bookId = cmd.CreateParameter()
    p_bookId.ParameterName <- "@book_id"
    p_bookId.Value <- box bookId
    cmd.Parameters.Add(p_bookId) |> ignore
    cmd.ExecuteNonQuery()

  member this.updateBookISBN(title: string, tags: string, isbn: string, bookId: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.updateBookISBN
    let p_title = cmd.CreateParameter()
    p_title.ParameterName <- "@title"
    p_title.Value <- box title
    cmd.Parameters.Add(p_title) |> ignore
    let p_tags = cmd.CreateParameter()
    p_tags.ParameterName <- "@tags"
    p_tags.Value <- box tags
    cmd.Parameters.Add(p_tags) |> ignore
    let p_isbn = cmd.CreateParameter()
    p_isbn.ParameterName <- "@isbn"
    p_isbn.Value <- box isbn
    cmd.Parameters.Add(p_isbn) |> ignore
    let p_bookId = cmd.CreateParameter()
    p_bookId.ParameterName <- "@book_id"
    p_bookId.Value <- box bookId
    cmd.Parameters.Add(p_bookId) |> ignore
    cmd.ExecuteNonQuery()

  member this.deleteAuthorBeforeYear(yr: int, authorId: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.deleteAuthorBeforeYear
    let p_yr = cmd.CreateParameter()
    p_yr.ParameterName <- "@yr"
    p_yr.Value <- box yr
    cmd.Parameters.Add(p_yr) |> ignore
    let p_authorId = cmd.CreateParameter()
    p_authorId.ParameterName <- "@author_id"
    p_authorId.Value <- box authorId
    cmd.Parameters.Add(p_authorId) |> ignore
    cmd.ExecuteNonQuery()
