// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace Booktest

open System
open System.Data

module Readers =

  let authorReader (r: IDataReader) : Author =
    {
      Author.AuthorId = r.GetInt32(r.GetOrdinal("author_id"))
      Name = r.GetString(r.GetOrdinal("name"))
    }

  let bookReader (r: IDataReader) : Book =
    {
      Book.BookId = r.GetInt32(r.GetOrdinal("book_id"))
      AuthorId = r.GetInt32(r.GetOrdinal("author_id"))
      Isbn = r.GetString(r.GetOrdinal("isbn"))
      BookType = r.GetString(r.GetOrdinal("book_type"))
      Title = r.GetString(r.GetOrdinal("title"))
      Yr = r.GetInt32(r.GetOrdinal("yr"))
      Available = r.GetDateTime(r.GetOrdinal("available"))
      Tags = r.GetString(r.GetOrdinal("tags"))
    }

  let booksByTagsRowReader (r: IDataReader) : BooksByTagsRow =
    {
      BooksByTagsRow.BookId = r.GetInt32(r.GetOrdinal("book_id"))
      Title = r.GetString(r.GetOrdinal("title"))
      Name = if r.IsDBNull(r.GetOrdinal("name")) then None else Some(r.GetString(r.GetOrdinal("name")))
      Isbn = r.GetString(r.GetOrdinal("isbn"))
      Tags = r.GetString(r.GetOrdinal("tags"))
    }
