// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace SAuthors

open System
open System.Runtime.InteropServices
open System.Data

type Author =
  {
    Id: int64
    Name: string
    Bio: string option
    Address: string option
    DateOfBirth: DateTime option
    LastTs: DateTimeOffset option
    SavingsAmt: double option
    LoanAmt: decimal option
    Disabled: bool option
    Married: bool option
    Payable: decimal option
  }

type Embedding = { Id: int64; Embedding: float32[] }

type Event = { Id: int64; Type: string; Val: string option }

type GetAuthor2Row = { Id: int64; Name: string; Bio: string option }

type TotalBooksRow = { Cnt: int64; TotalBooks: double option }
