// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace SAuthors

open System
open System.Runtime.InteropServices
open System.Data
open SAuthors.Readers

module Sqls =

  [<Literal>]
  let getAuthor2 =
    """
    SELECT id, name, bio FROM authors
WHERE id = @id LIMIT 1
  """

  [<Literal>]
  let getAuthor =
    """
    SELECT id, name, bio, address, date_of_birth, last_ts, savings_amt, loan_amt, disabled, married, payable FROM authors
WHERE id = @id LIMIT 1
  """

  [<Literal>]
  let listAuthors =
    """
    SELECT id, name, bio, address, date_of_birth, last_ts, savings_amt, loan_amt, disabled, married, payable FROM authors
ORDER BY name
  """

  [<Literal>]
  let createAuthor =
    """
    INSERT INTO authors (
  name, bio
) VALUES (
  @name, @bio
)
RETURNING id, name, bio, address, date_of_birth, last_ts, savings_amt, loan_amt, disabled, married, payable
  """

  [<Literal>]
  let deleteAuthor =
    """
    DELETE FROM authors
WHERE id = @id
  """

  [<Literal>]
  let countAuthors =
    """
    SELECT count(*) as cnt from authors
  """

  [<Literal>]
  let totalBooks =
    """
    SELECT count(*) as cnt, sum(id) as total_books from authors
  """

  [<Literal>]
  let dbString =
    """
    SELECT 'Hello world' as str
  """

  [<Literal>]
  let getEmbedding =
    """
    ;

SELECT id, embedding FROM embeddings
WHERE id = @id LIMIT 1
  """

  [<Literal>]
  let createEmbedding =
    """
    INSERT INTO embeddings (
  embedding
) VALUES (
  @embedding
)
RETURNING id, embedding
  """

  [<Literal>]
  let createEvent =
    """
    INSERT INTO events (
  type, val
) VALUES (
  @type, @val
)
RETURNING id, type, val
  """

  [<Literal>]
  let getEventsByType =
    """
    SELECT id, type, val FROM events
WHERE type = @type
ORDER BY id
  """

  [<Literal>]
  let maxAuthorId =
    """
    SELECT CAST(max(id) AS INTEGER) as max_id from authors
  """

  [<Literal>]
  let getAuthorsByIds =
    """
    SELECT id, name, bio, address, date_of_birth, last_ts, savings_amt, loan_amt, disabled, married, payable FROM authors
WHERE id IN (/*SLICE:ids*/)
ORDER BY id
  """

[<RequireQualifiedAccessAttribute>]
type DB(conn: IDbConnection) =

  member _.GetAuthor2(id: int64) =

    use cmd = conn.CreateCommand()

    cmd.Parameters.Add(cmd.CreateParameter(ParameterName = "@id", Value = box id))
    |> ignore

    cmd.CommandText <- Sqls.getAuthor2
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(getAuthor2RowReader rdr) else ValueNone

  member _.GetAuthor(id: int64) =

    use cmd = conn.CreateCommand()

    cmd.Parameters.Add(cmd.CreateParameter(ParameterName = "@id", Value = box id))
    |> ignore

    cmd.CommandText <- Sqls.getAuthor
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(authorReader rdr) else ValueNone

  member _.ListAuthors() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.listAuthors
    use rdr = cmd.ExecuteReader()
    let results = ResizeArray()

    while rdr.Read() do
      results.Add(authorReader rdr)

    results

  member _.CreateAuthor(name: string, ?bio: string) =

    use cmd = conn.CreateCommand()

    cmd.Parameters.Add(cmd.CreateParameter(ParameterName = "@name", Value = box name))
    |> ignore

    cmd.Parameters.Add(
      cmd.CreateParameter(
        ParameterName = "@bio",
        Value =
          match bio with
          | Some v -> box v
          | None -> box DBNull.Value
      )
    )
    |> ignore

    cmd.CommandText <- Sqls.createAuthor
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(authorReader rdr) else ValueNone

  member _.DeleteAuthor(id: int64) =

    use cmd = conn.CreateCommand()

    cmd.Parameters.Add(cmd.CreateParameter(ParameterName = "@id", Value = box id))
    |> ignore

    cmd.CommandText <- Sqls.deleteAuthor
    cmd.ExecuteNonQuery()

  member _.CountAuthors() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.countAuthors
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(rdr.GetInt64(rdr.GetOrdinal("cnt"))) else ValueNone

  member _.TotalBooks() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.totalBooks
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(totalBooksRowReader rdr) else ValueNone

  member _.DbString() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.dbString
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(rdr.GetString(rdr.GetOrdinal("str"))) else ValueNone

  member _.GetEmbedding(id: int64) =

    use cmd = conn.CreateCommand()

    cmd.Parameters.Add(cmd.CreateParameter(ParameterName = "@id", Value = box id))
    |> ignore

    cmd.CommandText <- Sqls.getEmbedding
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(embeddingReader rdr) else ValueNone

  member _.CreateEmbedding(embedding: float32[]) =

    use cmd = conn.CreateCommand()

    cmd.Parameters.Add(
      cmd.CreateParameter(
        ParameterName = "@embedding",
        Value = box (MemoryMarshal.AsBytes<float32>(ReadOnlySpan<float32>(embedding)).ToArray())
      )
    )
    |> ignore

    cmd.CommandText <- Sqls.createEmbedding
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(embeddingReader rdr) else ValueNone

  member _.CreateEvent(``type``: string, ?``val``: string) =

    use cmd = conn.CreateCommand()

    cmd.Parameters.Add(cmd.CreateParameter(ParameterName = "@type", Value = box ``type``))
    |> ignore

    cmd.Parameters.Add(
      cmd.CreateParameter(
        ParameterName = "@val",
        Value =
          match ``val`` with
          | Some v -> box v
          | None -> box DBNull.Value
      )
    )
    |> ignore

    cmd.CommandText <- Sqls.createEvent
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(eventReader rdr) else ValueNone

  member _.GetEventsByType(``type``: string) =

    use cmd = conn.CreateCommand()

    cmd.Parameters.Add(cmd.CreateParameter(ParameterName = "@type", Value = box ``type``))
    |> ignore

    cmd.CommandText <- Sqls.getEventsByType
    use rdr = cmd.ExecuteReader()
    let results = ResizeArray()

    while rdr.Read() do
      results.Add(eventReader rdr)

    results

  member _.MaxAuthorId() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.maxAuthorId
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(rdr.GetInt64(rdr.GetOrdinal("max_id"))) else ValueNone

  member _.GetAuthorsByIds(ids: int64 seq) =

    use cmd = conn.CreateCommand()
    let mutable commandText = Sqls.getAuthorsByIds
    let idsPlaceholders = ids |> Seq.mapi (fun i _ -> sprintf "@ids_%d" i) |> String.concat ", "

    commandText <-
      if Seq.isEmpty ids then
        commandText.Replace("/*SLICE:ids*/", "NULL")
      else
        commandText.Replace("/*SLICE:ids*/", idsPlaceholders)

    ids
    |> Seq.iteri (fun i v ->
      cmd.Parameters.Add(cmd.CreateParameter(ParameterName = (sprintf "@ids_%d" i), Value = box v))
      |> ignore
    )

    cmd.CommandText <- commandText
    use rdr = cmd.ExecuteReader()
    let results = ResizeArray()

    while rdr.Read() do
      results.Add(authorReader rdr)

    results
