// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace SAuthors

open System
open System.Data
open SAuthors.Readers

module Sqls =

  [<Literal>]
  let getAuthor2 =
    """
    SELECT id, name, bio FROM authors
WHERE id = @id LIMIT 1
  """

  [<Literal>]
  let getAuthor =
    """
    SELECT id, name, bio, address, date_of_birth, last_ts, savings_amt, loan_amt, disabled, married, payable FROM authors
WHERE id = @id LIMIT 1
  """

  [<Literal>]
  let listAuthors =
    """
    SELECT id, name, bio, address, date_of_birth, last_ts, savings_amt, loan_amt, disabled, married, payable FROM authors
ORDER BY name
  """

  [<Literal>]
  let createAuthor =
    """
    INSERT INTO authors (
  name, bio
) VALUES (
  @name, @bio
)
RETURNING id, name, bio, address, date_of_birth, last_ts, savings_amt, loan_amt, disabled, married, payable
  """

  [<Literal>]
  let deleteAuthor =
    """
    DELETE FROM authors
WHERE id = @id
  """

  [<Literal>]
  let countAuthors =
    """
    SELECT count(*) as cnt from authors
  """

  [<Literal>]
  let totalBooks =
    """
    SELECT count(*) as cnt, sum(id) as total_books from authors
  """

  [<Literal>]
  let dbString =
    """
    SELECT 'Hello world' as str
  """

[<RequireQualifiedAccessAttribute>]
type DB(conn: IDbConnection) =

  member this.getAuthor2(id: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.getAuthor2

    cmd.Parameters.Add(cmd.CreateParameter(ParameterName = "@id", Value = box id))
    |> ignore

    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(getAuthor2RowReader rdr) else ValueNone

  member this.getAuthor(id: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.getAuthor

    cmd.Parameters.Add(cmd.CreateParameter(ParameterName = "@id", Value = box id))
    |> ignore

    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(authorReader rdr) else ValueNone

  member this.listAuthors() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.listAuthors
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (authorReader rdr) :: results

    List.rev results

  member this.createAuthor(name: string, ?bio: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.createAuthor

    cmd.Parameters.Add(cmd.CreateParameter(ParameterName = "@name", Value = box name))
    |> ignore

    cmd.Parameters.Add(
      cmd.CreateParameter(
        ParameterName = "@bio",
        Value =
          match bio with
          | Some v -> box v
          | None -> box DBNull.Value
      )
    )
    |> ignore

    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(authorReader rdr) else ValueNone

  member this.deleteAuthor(id: int) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.deleteAuthor

    cmd.Parameters.Add(cmd.CreateParameter(ParameterName = "@id", Value = box id))
    |> ignore

    cmd.ExecuteNonQuery()

  member this.countAuthors() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.countAuthors
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(rdr.GetInt32(rdr.GetOrdinal("cnt"))) else ValueNone

  member this.totalBooks() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.totalBooks
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(totalBooksRowReader rdr) else ValueNone

  member this.dbString() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.dbString
    use rdr = cmd.ExecuteReader()
    if rdr.Read() then ValueSome(rdr.GetString(rdr.GetOrdinal("str"))) else ValueNone
