// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace SAuthors

open System
open System.Runtime.InteropServices
open System.Data

module Readers =

  let getAuthor2RowReader (r: IDataReader) : GetAuthor2Row =
    {
      GetAuthor2Row.Id = r.GetInt32(r.GetOrdinal("id"))
      Name = r.GetString(r.GetOrdinal("name"))
      Bio = if r.IsDBNull(r.GetOrdinal("bio")) then None else Some(r.GetString(r.GetOrdinal("bio")))
    }

  let authorReader (r: IDataReader) : Author =
    {
      Author.Id = r.GetInt32(r.GetOrdinal("id"))
      Name = r.GetString(r.GetOrdinal("name"))
      Bio = if r.IsDBNull(r.GetOrdinal("bio")) then None else Some(r.GetString(r.GetOrdinal("bio")))
      Address = if r.IsDBNull(r.GetOrdinal("address")) then None else Some(r.GetString(r.GetOrdinal("address")))
      DateOfBirth =
        if r.IsDBNull(r.GetOrdinal("date_of_birth")) then None else Some(r.GetDateTime(r.GetOrdinal("date_of_birth")))
      LastTs =
        if r.IsDBNull(r.GetOrdinal("last_ts")) then
          None
        else
          Some(DateTimeOffset(r.GetDateTime(r.GetOrdinal("last_ts"))))
      SavingsAmt =
        if r.IsDBNull(r.GetOrdinal("savings_amt")) then None else Some(r.GetDouble(r.GetOrdinal("savings_amt")))
      LoanAmt = if r.IsDBNull(r.GetOrdinal("loan_amt")) then None else Some(r.GetDecimal(r.GetOrdinal("loan_amt")))
      Disabled = if r.IsDBNull(r.GetOrdinal("disabled")) then None else Some(r.GetBoolean(r.GetOrdinal("disabled")))
      Married = if r.IsDBNull(r.GetOrdinal("married")) then None else Some(r.GetBoolean(r.GetOrdinal("married")))
      Payable = if r.IsDBNull(r.GetOrdinal("payable")) then None else Some(r.GetDecimal(r.GetOrdinal("payable")))
    }

  let totalBooksRowReader (r: IDataReader) : TotalBooksRow =
    {
      TotalBooksRow.Cnt = r.GetInt32(r.GetOrdinal("cnt"))
      TotalBooks =
        if r.IsDBNull(r.GetOrdinal("total_books")) then None else Some(r.GetDouble(r.GetOrdinal("total_books")))
    }

  let embeddingReader (r: IDataReader) : Embedding =
    {
      Embedding.Id = r.GetInt32(r.GetOrdinal("id"))
      Embedding =
        MemoryMarshal
          .Cast<byte, float32>(ReadOnlySpan<byte>(r.GetValue(r.GetOrdinal("embedding")) :?> byte[]))
          .ToArray()
    }

  let eventReader (r: IDataReader) : Event =
    {
      Event.Id = r.GetInt32(r.GetOrdinal("id"))
      Type = r.GetString(r.GetOrdinal("type"))
      Val = if r.IsDBNull(r.GetOrdinal("val")) then None else Some(r.GetString(r.GetOrdinal("val")))
    }
