// Code generated by qtc from "models.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:1
package templates

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:1
import (
	"github.com/kaashyapan/sqlc-gen-fsharp/internal/core"
	"github.com/tabbed/sqlc-go/sdk"
)

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:7
func StreamModels(qw422016 *qt422016.Writer, ctx core.TmplCtx) {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:7
	qw422016.N().S(`// Code generated by sqlc. DO NOT EDIT.
// version: sqlc `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:9
	qw422016.E().S(ctx.SqlcVersion)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:9
	qw422016.N().S(`

namespace `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:11
	qw422016.E().S(ctx.Package)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:11
	qw422016.N().S(`

`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:13
	for _, mod := range core.Imports(ctx.SourceName, ctx.Package) {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:13
		qw422016.N().S(`open `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:14
		qw422016.E().S(mod)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:14
		qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:15
	}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:15
	qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:17
	for _, recordType := range ctx.DataClasses {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:17
		qw422016.N().S(`
type `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:18
		qw422016.E().S(recordType.Name)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:18
		qw422016.N().S(` = 
    {
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:20
		for _, field := range recordType.Fields {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:20
			qw422016.N().S(`        `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:21
			qw422016.E().S(sdk.Title(field.Name))
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:21
			qw422016.N().S(` : `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:21
			qw422016.E().S(field.Type.Name)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:21
			qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:22
		}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:22
		qw422016.N().S(`    }
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:24
	}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:24
	qw422016.N().S(`

`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:26
	for _, q := range ctx.Queries {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:26
		qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:27
		if q.Ret.EmitStruct() {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:27
			qw422016.N().S(`
type `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:28
			qw422016.E().S(q.Ret.Type())
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:28
			qw422016.N().S(` = 
    {
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:30
			for _, f := range q.Ret.Struct.Fields {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:30
				qw422016.N().S(`        `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:31
				qw422016.E().S(sdk.Title(f.Name))
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:31
				qw422016.N().S(` : `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:31
				qw422016.E().S(f.Type.String())
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:31
				qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:32
			}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:32
			qw422016.N().S(`    }
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:34
		}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:34
		qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:35
	}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:35
	qw422016.N().S(`

`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
}

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
func WriteModels(qq422016 qtio422016.Writer, ctx core.TmplCtx) {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
	StreamModels(qw422016, ctx)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
}

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
func Models(ctx core.TmplCtx) string {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
	WriteModels(qb422016, ctx)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
	qs422016 := string(qb422016.B)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
	return qs422016
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/models.qtpl:37
}
