// Code generated by qtc from "queries.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:1
package templates

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:1
import (
	"github.com/kaashyapan/sqlc-gen-fsharp/internal/core"
)

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:6
func StreamQueries(qw422016 *qt422016.Writer, ctx core.TmplCtx) {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:6
	qw422016.N().S(`// Code generated by sqlc. DO NOT EDIT.
// version: sqlc `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:8
	qw422016.E().S(ctx.SqlcVersion)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:8
	qw422016.N().S(`



namespace `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:12
	qw422016.E().S(ctx.Package)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:12
	qw422016.N().S(`

`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:14
	for _, mod := range core.Imports(ctx.SourceName, ctx.Package) {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:14
		qw422016.N().S(`open `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:15
		qw422016.E().S(mod)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:15
		qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:16
	}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:16
	qw422016.N().S(`
module Sqls = 
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:19
	for _, query := range ctx.Queries {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:19
		qw422016.N().S(`
  [<Literal>]
  let `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:21
		qw422016.N().S(query.ConstantName)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:21
		qw422016.N().S(` =
    """
    `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:23
		qw422016.N().S(query.SQL)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:23
		qw422016.N().S(`
  """
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:25
	}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:25
	qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:27
	connstr := ctx.ConnString()

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:28
	qw422016.N().S(`
[<RequireQualifiedAccessAttribute>]
type DB (conn: IDbConnection) =
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:31
	for _, line := range connstr {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:31
		qw422016.N().S(`  `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:32
		qw422016.N().S(line)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:32
		qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:33
	}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:33
	qw422016.N().S(`

`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:36
	for _, query := range ctx.Queries {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:36
		qw422016.N().S(`
  `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:38
		pipelines := ctx.ConnPipeline(query)

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:39
		qw422016.N().S(`

`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:41
		for _, line := range query.Comments {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:41
			qw422016.N().S(`  ///`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:42
			qw422016.N().S(line)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:42
			qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:43
		}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:43
		qw422016.N().S(`  member this.`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:44
		qw422016.E().S(query.ConstantName)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:44
		qw422016.N().S(`  (`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:44
		qw422016.E().S(query.Arg.Args())
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:44
		qw422016.N().S(`) =

`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:46
		for _, line := range pipelines {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:46
			qw422016.N().S(`    `)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:47
			qw422016.N().S(line)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:47
			qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:48
		}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:48
		qw422016.N().S(`
`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:50
	}
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:50
	qw422016.N().S(`

`)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
}

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
func WriteQueries(qq422016 qtio422016.Writer, ctx core.TmplCtx) {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
	StreamQueries(qw422016, ctx)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
	qt422016.ReleaseWriter(qw422016)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
}

//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
func Queries(ctx core.TmplCtx) string {
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
	qb422016 := qt422016.AcquireByteBuffer()
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
	WriteQueries(qb422016, ctx)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
	qs422016 := string(qb422016.B)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
	qt422016.ReleaseByteBuffer(qb422016)
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
	return qs422016
//line /home/nordfjord/git/vocal/sqlc-gen-fsharp/internal/templates/queries.qtpl:52
}
