// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace Ondeck

open System
open System.Data

type City = { Slug: string; Name: string }

type Venue =
  {
    Id: int
    Status: string
    Statuses: string option
    Slug: string
    Name: string
    City: string
    SpotifyPlaylist: string
    SongkickId: string option
    Tags: string option
    CreatedAt: DateTime
  }

type VenueCountByCityRow = { City: string; Count: int }
