// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace Ondeck

open System
open System.Data
open Ondeck.Readers

module Sqls =

  [<Literal>]
  let listCities =
    """
    SELECT slug, name
FROM city
ORDER BY name
  """

  [<Literal>]
  let getCity =
    """
    SELECT slug, name
FROM city
WHERE slug = ?
  """

  [<Literal>]
  let createCity =
    """
    INSERT INTO city (
    name,
    slug
) VALUES (
    ?,
    ? 
)
  """

  [<Literal>]
  let updateCityName =
    """
    UPDATE city
SET name = ?
WHERE slug = ?
  """

  [<Literal>]
  let listVenues =
    """
    SELECT id, status, statuses, slug, name, city, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE city = ?
ORDER BY name
  """

  [<Literal>]
  let deleteVenue =
    """
    DELETE FROM venue
WHERE slug = ? AND slug = ?
  """

  [<Literal>]
  let getVenue =
    """
    SELECT id, status, statuses, slug, name, city, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE slug = ? AND city = ?
  """

  [<Literal>]
  let createVenue =
    """
    INSERT INTO venue (
    slug,
    name,
    city,
    created_at,
    spotify_playlist,
    status,
    statuses,
    tags
) VALUES (
    ?,
    ?,
    ?,
    CURRENT_TIMESTAMP,
    ?,
    ?,
    ?,
    ?
)
  """

  [<Literal>]
  let updateVenueName =
    """
    UPDATE venue
SET name = ?
WHERE slug = ?
  """

  [<Literal>]
  let venueCountByCity =
    """
    SELECT
    city,
    count(*)
FROM venue
GROUP BY 1
ORDER BY 1
  """

[<RequireQualifiedAccessAttribute>]
type DB(conn: IDbConnection) =

  member this.listCities() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.listCities
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (cityReader rdr) :: results

    List.rev results

  member this.getCity(slug: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.getCity
    let p_slug = cmd.CreateParameter()
    p_slug.ParameterName <- "@slug"
    p_slug.Value <- box slug
    cmd.Parameters.Add(p_slug) |> ignore
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (cityReader rdr) :: results

    List.rev results

  member this.createCity(name: string, slug: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.createCity
    let p_name = cmd.CreateParameter()
    p_name.ParameterName <- "@name"
    p_name.Value <- box name
    cmd.Parameters.Add(p_name) |> ignore
    let p_slug = cmd.CreateParameter()
    p_slug.ParameterName <- "@slug"
    p_slug.Value <- box slug
    cmd.Parameters.Add(p_slug) |> ignore
    cmd.ExecuteNonQuery()

  member this.updateCityName(name: string, slug: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.updateCityName
    let p_name = cmd.CreateParameter()
    p_name.ParameterName <- "@name"
    p_name.Value <- box name
    cmd.Parameters.Add(p_name) |> ignore
    let p_slug = cmd.CreateParameter()
    p_slug.ParameterName <- "@slug"
    p_slug.Value <- box slug
    cmd.Parameters.Add(p_slug) |> ignore
    cmd.ExecuteNonQuery()

  member this.listVenues(city: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.listVenues
    let p_city = cmd.CreateParameter()
    p_city.ParameterName <- "@city"
    p_city.Value <- box city
    cmd.Parameters.Add(p_city) |> ignore
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (venueReader rdr) :: results

    List.rev results

  member this.deleteVenue(slug: string, slug_2: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.deleteVenue
    let p_slug = cmd.CreateParameter()
    p_slug.ParameterName <- "@slug"
    p_slug.Value <- box slug
    cmd.Parameters.Add(p_slug) |> ignore
    let p_slug_2 = cmd.CreateParameter()
    p_slug_2.ParameterName <- "@slug"
    p_slug_2.Value <- box slug_2
    cmd.Parameters.Add(p_slug_2) |> ignore
    cmd.ExecuteNonQuery()

  member this.getVenue(slug: string, city: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.getVenue
    let p_slug = cmd.CreateParameter()
    p_slug.ParameterName <- "@slug"
    p_slug.Value <- box slug
    cmd.Parameters.Add(p_slug) |> ignore
    let p_city = cmd.CreateParameter()
    p_city.ParameterName <- "@city"
    p_city.Value <- box city
    cmd.Parameters.Add(p_city) |> ignore
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (venueReader rdr) :: results

    List.rev results

  member this.createVenue
    (slug: string, name: string, city: string, spotifyPlaylist: string, status: string, ?statuses: string, ?tags: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.createVenue
    let p_slug = cmd.CreateParameter()
    p_slug.ParameterName <- "@slug"
    p_slug.Value <- box slug
    cmd.Parameters.Add(p_slug) |> ignore
    let p_name = cmd.CreateParameter()
    p_name.ParameterName <- "@name"
    p_name.Value <- box name
    cmd.Parameters.Add(p_name) |> ignore
    let p_city = cmd.CreateParameter()
    p_city.ParameterName <- "@city"
    p_city.Value <- box city
    cmd.Parameters.Add(p_city) |> ignore
    let p_spotifyPlaylist = cmd.CreateParameter()
    p_spotifyPlaylist.ParameterName <- "@spotify_playlist"
    p_spotifyPlaylist.Value <- box spotifyPlaylist
    cmd.Parameters.Add(p_spotifyPlaylist) |> ignore
    let p_status = cmd.CreateParameter()
    p_status.ParameterName <- "@status"
    p_status.Value <- box status
    cmd.Parameters.Add(p_status) |> ignore
    let p_statuses = cmd.CreateParameter()
    p_statuses.ParameterName <- "@statuses"

    p_statuses.Value <-
      match statuses with
      | Some v -> box v
      | None -> box DBNull.Value

    cmd.Parameters.Add(p_statuses) |> ignore
    let p_tags = cmd.CreateParameter()
    p_tags.ParameterName <- "@tags"

    p_tags.Value <-
      match tags with
      | Some v -> box v
      | None -> box DBNull.Value

    cmd.Parameters.Add(p_tags) |> ignore
    cmd.ExecuteNonQuery()

  member this.updateVenueName(name: string, slug: string) =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.updateVenueName
    let p_name = cmd.CreateParameter()
    p_name.ParameterName <- "@name"
    p_name.Value <- box name
    cmd.Parameters.Add(p_name) |> ignore
    let p_slug = cmd.CreateParameter()
    p_slug.ParameterName <- "@slug"
    p_slug.Value <- box slug
    cmd.Parameters.Add(p_slug) |> ignore
    cmd.ExecuteNonQuery()

  member this.venueCountByCity() =

    use cmd = conn.CreateCommand()
    cmd.CommandText <- Sqls.venueCountByCity
    use rdr = cmd.ExecuteReader()
    let mutable results = []

    while rdr.Read() do
      results <- (venueCountByCityRowReader rdr) :: results

    List.rev results
