// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.30.0

namespace Ondeck

open System
open System.Data

module Readers =

  let cityReader (r: IDataReader) : City =
    { City.Slug = r.GetString(r.GetOrdinal("slug")); Name = r.GetString(r.GetOrdinal("name")) }

  let venueReader (r: IDataReader) : Venue =
    {
      Venue.Id = r.GetInt32(r.GetOrdinal("id"))
      Status = r.GetString(r.GetOrdinal("status"))
      Statuses = if r.IsDBNull(r.GetOrdinal("statuses")) then None else Some(r.GetString(r.GetOrdinal("statuses")))
      Slug = r.GetString(r.GetOrdinal("slug"))
      Name = r.GetString(r.GetOrdinal("name"))
      City = r.GetString(r.GetOrdinal("city"))
      SpotifyPlaylist = r.GetString(r.GetOrdinal("spotify_playlist"))
      SongkickId =
        if r.IsDBNull(r.GetOrdinal("songkick_id")) then None else Some(r.GetString(r.GetOrdinal("songkick_id")))
      Tags = if r.IsDBNull(r.GetOrdinal("tags")) then None else Some(r.GetString(r.GetOrdinal("tags")))
      CreatedAt = r.GetDateTime(r.GetOrdinal("created_at"))
    }

  let venueCountByCityRowReader (r: IDataReader) : VenueCountByCityRow =
    {
      VenueCountByCityRow.City = r.GetString(r.GetOrdinal("city"))
      Count = r.GetInt32(r.GetOrdinal("count"))
    }
